export const apiEndPoint = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  CURRENT_USER: "/auth/getCurrentUser",
  GET_FUNCTION: "/functions/list",
  CREATE_FUNTION: "/functions/create",
  UPDATE_FUNCTION: (id: string) => `/functions/update/${id}`,
  DELETE_FUNCTION: (id: string) => `/functions/delete/${id}`,
  GET_PARENT: "/parents/list",
  CREATE_PARENT: "/parents/create",
  UPDATE_PARENT: (id: string) => `/parents/update/${id}`,
  DELETE_PARENT: (id: string) => `/parents/delete/${id}`,
  GET_ROLE_LIST: "/roles/list",
  GET_ROLE_BY_ID: (id: string) => `/roles/getByID/${id}`,
  CREATE_ROLE: "/roles/create",
  UPDATE_ROLE: (id: string) => `/roles/update/${id}`,
  DELETE_ROLE: (id: string) => `/roles/delete/${id}`,
  GET_LIST_FUNCTION: "/roles/listFunction",
  GET_LIST_MODULE: "/roles/listModule",
  GET_LIST_STUDENT: "/students/list",
  GET_LIST_STAFF: "/staffs/list",
  CREATE_STUDENT: "/students/create",
  CREATE_STAFF: "/staffs/create",
  UPDATE_STUDENT: (id: string) => `/students/update/${id}`,
  UPDATE_STAFF: (id: string) => `/staffs/update/${id}`,
  DELETE_STUDENT: (id: string) => `/students/delete/${id}`,
  DELETE_STAFF: (id: string) => `/staffs/delete/${id}`,
  GET_ACCOUNT_LIST: '/accounts/list',
  UPDATE_ACCOUNT: (id: string) => `/accounts/update/${id}`,
  DELETE_ACCOUNT: (id: string) => `/accounts/delete/${id}`,
  GET_ROLE_NAME_LIST: "/accounts/roleNames",
  REGISTER_ENROLLMENT: '/enrollments/registerEnroll',
  GET_ENROLLMENT_LIST: '/enrollments/list',
  GET_ENROLLMENT_BY_ID: (id: string) => `/enrollments/getById/${id}`,
  UPLOAD_PDF: "/enrollments/uploadPDF",
  GET_PDF_BY_ID: (id: string) => `/enrollments/pdf/${id}`,
  APPROVE_ENROLLMENT: "/enrollments/aprrovedEnroll",
  UPDATE_ENROLLMENT: (id: string) => `/enrollments/update/${id}`,
  REJECT_ENROLLMENT: (id: string) => `/enrollments/rejectEnroll/${id}`,
  APPROVE_ALL_ENROLLMENT: "/enrollments/approvedEnrollAll",
  GET_LIST_MENU: "/menus/list",
  CREATE_MENU: "/menus/create",
  DELETE_MENU: (menuId: string) => `/menus/delete/${menuId}`,
  GET_MENU_BY_ID: (menuId: string) => `/menus/get-by-id/${menuId}`,
  GET_SCHOOLYEARS_LIST: '/schoolYears/list',
  CREATE_SCHOOLYEAR: '/schoolYears/create',
  UPDATE_SCHOOLYEAR: (id: string) => `/schoolYears/update/${id}`,
  DELETE_SCHOOLYEAR: (id: string) => `/schoolYears/delete/${id}`,
  GET_SCHOOLYEAR_BY_ID: (id: string) => `/schoolYears/getById/${id}`,
  END_SCHOOLYEAR: (id: string) => `/schoolYears/endSchoolYear/${id}`,
  SCHOOLYEAR_REPORT: '/schoolYears/getStudentGraduated'
};

export const apiConfig = {
  // baseURL: import.meta.env.VITE_API_URL_PROD || "https://kingdergarten-api-gmena8b7cug2f4cr.southeastasia-01.azurewebsites.net/api/pms/",
  baseURL: import.meta.env.VITE_API_URL,
}
