export const apiEndPoint = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  CURRENT_USER: "/auth/getCurrentUser",
  GET_FUNCTION: "/functions/list",
  CREATE_FUNTION: "/functions/create",
  UPDATE_FUNCTION: (id: string) => `/functions/update/${id}`,
  DELETE_FUNCTION: (id: string) => `/functions/delete/${id}`,
  GET_PARENT: "/parents/list",
  CREATE_PARENT: "/parents/create",
  UPDATE_PARENT: (id: string) => `/parents/update/${id}`,
  DELETE_PARENT: (id: string) => `/parents/delete/${id}`,
  GET_ROLE_LIST: "/roles/list",
  GET_ROLE_BY_ID: (id: string) => `/roles/getByID/${id}`,
  CREATE_ROLE: "/roles/create",
  UPDATE_ROLE: (id: string) => `/roles/update/${id}`,
  DELETE_ROLE: (id: string) => `/roles/delete/${id}`,
  GET_LIST_FUNCTION: "/roles/listFunction",
  GET_LIST_MODULE: "/roles/listModule",
  GET_LIST_STUDENT: "/students/list",
  CREATE_STUDENT: "/students/create",
  UPDATE_STUDENT: (id: string) => `/students/update/${id}`,
  DELETE_STUDENT: (id: string) => `/students/delete/${id}`,
  GET_ACCOUNT_LIST: '/accounts/list',
  UPDATE_ACCOUNT: (id: string) => `/accounts/update/${id}`,
  DELETE_ACCOUNT: (id: string) => `/accounts/delete/${id}`,
  GET_ROLE_NAME_LIST: "/accounts/roleNames",
};
