export enum Permission {
    ADMIN = 'admin',
    USER = 'user',
    GUEST = 'guest',
    TEACHER = 'teacher',
    PARENT = 'parent',
    ACADEMIC_STAFF = 'academic_staff',

    VIEW_CLASS = 'view_class',
    EDIT_CLASS = 'edit_class',
    DELETE_CLASS = 'delete_class',
    CREATE_CLASS = 'create_class',

    VIEW_STUDENT = 'view_student',
    EDIT_STUDENT = 'edit_student',
    DELETE_STUDENT = 'delete_student',
    CREATE_STUDENT = 'create_student',
    VIEW_TEACHER = 'view_teacher',
    EDIT_TEACHER = 'edit_teacher',
    DELETE_TEACHER = 'delete_teacher',
    CREATE_TEACHER = 'create_teacher',
    VIEW_PARENT = 'view_parent',
    EDIT_PARENT = 'edit_parent',
    DELETE_PARENT = 'delete_parent',
    CREATE_PARENT = 'create_parent',
    VIEW_ACADEMIC_STAFF = 'view_academic_staff',
    EDIT_ACADEMIC_STAFF = 'edit_academic_staff',
    DELETE_ACADEMIC_STAFF = 'delete_academic_staff',
    CREATE_ACADEMIC_STAFF = 'create_academic_staff',
}